# This workflow is to build the documentation 
# for Grihsvachalnam and published documentation
---

name: project site

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout project
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: install mkdocs
        run: pip install mkdocs
      - name: compile and generate the site
        run: mkdocs build
      - name: init new repo in site/ and add all files
        run: |
          cd site/
          git init
          git add -A
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Action"
          git config --global http.sslverify false
          git commit -m "Deploy"
          git branch -M main
          git push -f git@github.com:Amaya2024/griha-svachalnam.git main:gh-pages